version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/js-npm"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "npm"
  - package-ecosystem: "maven"
    directory: "/java-maven"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "maven" 